name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, ubuntu-latest]
        sys:
          - mingw64

    steps:
    - name: Install dependencies for Windows
      if: matrix.os == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        pacboy:

    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install cmake ninja-build g++ libgtest-dev

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset "x64-workflow"
