name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        location: C:/
        msystem: MINGW64
        pacboy:
          ninja
          gtest

    - name: Checkout Project
      uses: actions/checkout@v4


    - name: Setup MSYS env
      run: echo C:/msys64/mingw64/bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: CMake workflow        
      run: cmake --workflow --preset "GNUC"
