name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        pacboy:
          ninja
          gtest

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Echo
      env:
        PATH: '%PATH%;C:/msys64/mingw64/bin'
      run: gcm ninja

    - name: CMake workflow        
      run: cmake --workflow --preset "GNUC"
