name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, ubuntu-latest]
        c_compiler: [gcc]
        include:
        - os: windows-latest
          c_compiler: gcc
          cpp_compiler: g++

    steps:
    - name: Install dependencies for Windows
      if: matrix.os == 'windows-latest'
      run: |
        C:/msys64/usr/bin/pacman.exe -S lib mingw-w64-x86_64-gtest

    - name: Install dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install cmake ninja-build g++ libgtest-dev

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset "x64-workflow"
