name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: CMake workflow - Linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: cmake --workflow --preset "Linux-GNUC"
    
    - name: CMake workflow - Windows
      if: ${{ matrix.os }} == "windows-latest"
      run: cmake --workflow --preset "MinGW-GNUC"
