name: CI using CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        sys:
          - mingw64

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        update: true
        pacboy:
          cmake
          ninja
          gcc

    - name: Checkout Project
      uses: actions/checkout@v4

    - name: CMake workflow
      run: cmake --workflow --preset "MinGW-GNUC"
